openapi: 3.0.1
info:
  title: Devices API
  description: API for device management
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Development Server
#TODO: Adjuste post and PUT Example
paths:
  /devices:
    get:
      summary: Retrieve all devices
      operationId: getAllDevices
      responses:
        "200":
          description: Successfully retrieved the list of devices
    post:
      summary: Create a new device
      operationId: createDevice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Device"
      responses:
        "201":
          description: Device successfully created
  /devices/{id}:
    get:
      summary: Retrieve a specific device
      operationId: getDeviceById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Device found
        "404":
          description: Device not found
components:
  schemas:
    Device:
      type: object
      properties:
        name:
          type: string
        brand:
          type: string
        state:
          type: string
          enum:
            - AVAILABLE
            - IN_USE
            - INACTIVE